name: SSH Deploy Staged

on:
    push:
        branches:
            - main

jobs:
    remote-update:
        runs-on: ubuntu-latest

        steps:
            - name: Load SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: SSH and run deployment script
              run: |
                  ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
                  'sh ./stage.sh'
